library(ggplot2)
library(foreign)
memory.limit(size = 4095)
class.2 <- read.spss("C:\\Users\\icarlso1\\Simulation\\Programs\\LCA 2-Class\\Data\\LCA 2-Class se outlier 1.30.1.sav")
memory.limit(size = 4095)


!First, import the .csv file of parameter summaries, then assign the data to mydataf
mydataf <-


mydataf$indicators <- factor(mydataf$indicators,levels = c(1,2,3,4,5,6,7,8,9),labels = c("4", "5", "6" , "7", "8", "9", "10", "11", "12"))
mydataf$cov2 <- factor(mydataf$cov2,levels = c(1,2,3,4),labels = c("no covariate", "small covariate", "moderate covariate" , "large covariate"))
mydataf$observations <- factor(mydataf$observations,levels = c(1,2,3,4,5,6,7),labels = c("N = 70", "N = 100", "N = 200" , "N = 300", "N = 500", "N = 1000", "N = 2000"))

data111 <- subset(mydataf, se==1 & quality== 1 & in2==1)
data111c <- subset(mydataf, se==1 & quality==1 & cov != 1 & in2==1)

data211 <- subset(mydataf, se==2 & quality== 1 & in2==1)
data211c <- subset(mydataf, se==2 & quality==1 & cov != 1 & in2==1)

data121 <- subset(mydataf, se==1 & quality== 2 & in2==1)
data121c <- subset(mydataf, se==1 & quality==2 & cov != 1 & in2==1)

data221 <- subset(mydataf, se==2 & quality== 2 & in2==1)
data221c <- subset(mydataf, se==2 & quality==2 & cov != 1 & in2==1)

data112 <- subset(mydataf, se==1 & quality== 1 &is.na(seoutlier) & in2==1)
data112c <- subset(mydataf, se==1 & quality==1 & cov != 1 &is.na(seoutlier) & in2==1)

data212 <- subset(mydataf, se==2 & quality== 1 &is.na(seoutlier) & in2==1)
data212c <- subset(mydataf, se==2 & quality==1 & cov != 1 &is.na(seoutlier) & in2==1)

data122 <- subset(mydataf, se==1 & quality== 2 &is.na(seoutlier) & in2==1)
data122c <- subset(mydataf, se==1 & quality==2 & cov != 1 &is.na(seoutlier) & in2==1)

data222 <- subset(mydataf, se==2 & quality== 2 &is.na(seoutlier) & in2==1)
data222c <- subset(mydataf, se==2 & quality==2 & cov != 1 &is.na(seoutlier) & in2==1)

g.11L1prop1 <- ggplot(data111, aes(factor(indicators), L1prop))
g.11L1prop1 <- g.11L1prop1 + stat_boxplot()
g.11L1prop1 <- g.11L1prop1 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality L1prop SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_1_L1prop.png", width = 1000, height = 1000, units = 'px')
print(g.11L1prop1)
dev.off()
remove(g.11L1prop1)

g.12L1prop1 <- ggplot(data121, aes(factor(indicators), L1prop))
g.12L1prop1 <- g.12L1prop1 + stat_boxplot()
g.12L1prop1 <- g.12L1prop1 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality L1prop SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_1_L1prop.png", width = 1000, height = 1000, units = 'px')
print(g.12L1prop1)
dev.off()
remove(g.12L1prop1)

g.11L2prop1 <- ggplot(data111, aes(factor(indicators), L2prop))
g.11L2prop1 <- g.11L2prop1 + stat_boxplot()
g.11L2prop1 <- g.11L2prop1 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality L2prop SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_1_L2prop.png", width = 1000, height = 1000, units = 'px')
print(g.11L2prop1)
dev.off()
remove(g.11L2prop1)

g.12L2prop1 <- ggplot(data121, aes(factor(indicators), L2prop))
g.12L2prop1 <- g.12L2prop1 + stat_boxplot()
g.12L2prop1 <- g.12L2prop1 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality L2prop SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_1_L2prop.png", width = 1000, height = 1000, units = 'px')
print(g.12L2prop1)
dev.off()
remove(g.12L2prop1)

g.11CRPhiall1 <- ggplot(data111, aes(factor(indicators), CRPhiall))
g.11CRPhiall1 <- g.11CRPhiall1 + stat_boxplot()
g.11CRPhiall1 <- g.11CRPhiall1 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality CRPhiall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_1_CRPhiall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPhiall1)
dev.off()
remove(g.11CRPhiall1)

g.12CRPhiall1 <- ggplot(data121, aes(factor(indicators), CRPhiall))
g.12CRPhiall1 <- g.12CRPhiall1 + stat_boxplot()
g.12CRPhiall1 <- g.12CRPhiall1 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality CRPhiall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_1_CRPhiall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPhiall1)
dev.off()
remove(g.12CRPhiall1)

g.11CRPloall1 <- ggplot(data111, aes(factor(indicators), CRPloall))
g.11CRPloall1 <- g.11CRPloall1 + stat_boxplot()
g.11CRPloall1 <- g.11CRPloall1 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality CRPloall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_1_CRPloall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPloall1)
dev.off()
remove(g.11CRPloall1)

g.12CRPloall1 <- ggplot(data121, aes(factor(indicators), CRPloall))
g.12CRPloall1 <- g.12CRPloall1 + stat_boxplot()
g.12CRPloall1 <- g.12CRPloall1 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality CRPloall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_1_CRPloall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPloall1)
dev.off()
remove(g.12CRPloall1)

g.11gamma1 <- ggplot(data111, aes(factor(indicators), gamma))
g.11gamma1 <- ggplot(data111c, aes(factor(indicators), gamma))
g.11gamma1 <- g.11gamma1 + stat_boxplot()
g.11gamma1 <- g.11gamma1 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality gamma SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_1_gamma.png", width = 1000, height = 1000, units = 'px')
print(g.11gamma1)
dev.off()
remove(g.11gamma1)

g.12gamma1 <- ggplot(data121, aes(factor(indicators), gamma))
g.12gamma1 <- ggplot(data121c, aes(factor(indicators), gamma))
g.12gamma1 <- g.12gamma1 + stat_boxplot()
g.12gamma1 <- g.12gamma1 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality gamma SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_1_gamma.png", width = 1000, height = 1000, units = 'px')
print(g.12gamma1)
dev.off()
remove(g.12gamma1)

g.11L1propse1 <- ggplot(data111, aes(factor(indicators), L1propse))
g.11L1propse1 <- g.11L1propse1 + stat_boxplot()
g.11L1propse1 <- g.11L1propse1 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality L1propse SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_1_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.11L1propse1)
dev.off()
remove(g.11L1propse1)

g.21L1propse1 <- ggplot(data211, aes(factor(indicators), L1propse))
g.21L1propse1 <- g.21L1propse1 + stat_boxplot()
g.21L1propse1 <- g.21L1propse1 + facet_grid(cov2~observations) + opts(title = "2 Class MLR high quality L1propse SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.21included_1_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.21L1propse1)
dev.off()
remove(g.21L1propse1)

g.12L1propse1 <- ggplot(data121, aes(factor(indicators), L1propse))
g.12L1propse1 <- g.12L1propse1 + stat_boxplot()
g.12L1propse1 <- g.12L1propse1 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality L1propse SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_1_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.12L1propse1)
dev.off()
remove(g.12L1propse1)

g.22L1propse1 <- ggplot(data221, aes(factor(indicators), L1propse))
g.22L1propse1 <- g.22L1propse1 + stat_boxplot()
g.22L1propse1 <- g.22L1propse1 + facet_grid(cov2~observations) + opts(title = "2 Class MLR low quality L1propse SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.22included_1_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.22L1propse1)
dev.off()
remove(g.22L1propse1)

g.11CRPsehiall1 <- ggplot(data111, aes(factor(indicators), CRPsehiall))
g.11CRPsehiall1 <- g.11CRPsehiall1 + stat_boxplot()
g.11CRPsehiall1 <- g.11CRPsehiall1 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality CRPsehiall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_1_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPsehiall1)
dev.off()
remove(g.11CRPsehiall1)

g.21CRPsehiall1 <- ggplot(data211, aes(factor(indicators), CRPsehiall))
g.21CRPsehiall1 <- g.21CRPsehiall1 + stat_boxplot()
g.21CRPsehiall1 <- g.21CRPsehiall1 + facet_grid(cov2~observations) + opts(title = "2 Class MLR high quality CRPsehiall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.21included_1_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.21CRPsehiall1)
dev.off()
remove(g.21CRPsehiall1)

g.12CRPsehiall1 <- ggplot(data121, aes(factor(indicators), CRPsehiall))
g.12CRPsehiall1 <- g.12CRPsehiall1 + stat_boxplot()
g.12CRPsehiall1 <- g.12CRPsehiall1 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality CRPsehiall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_1_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPsehiall1)
dev.off()
remove(g.12CRPsehiall1)

g.22CRPsehiall1 <- ggplot(data221, aes(factor(indicators), CRPsehiall))
g.22CRPsehiall1 <- g.22CRPsehiall1 + stat_boxplot()
g.22CRPsehiall1 <- g.22CRPsehiall1 + facet_grid(cov2~observations) + opts(title = "2 Class MLR low quality CRPsehiall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.22included_1_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.22CRPsehiall1)
dev.off()
remove(g.22CRPsehiall1)

g.11CRPseloall1 <- ggplot(data111, aes(factor(indicators), CRPseloall))
g.11CRPseloall1 <- g.11CRPseloall1 + stat_boxplot()
g.11CRPseloall1 <- g.11CRPseloall1 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality CRPseloall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_1_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPseloall1)
dev.off()
remove(g.11CRPseloall1)

g.21CRPseloall1 <- ggplot(data211, aes(factor(indicators), CRPseloall))
g.21CRPseloall1 <- g.21CRPseloall1 + stat_boxplot()
g.21CRPseloall1 <- g.21CRPseloall1 + facet_grid(cov2~observations) + opts(title = "2 Class MLR high quality CRPseloall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.21included_1_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.21CRPseloall1)
dev.off()
remove(g.21CRPseloall1)

g.12CRPseloall1 <- ggplot(data121, aes(factor(indicators), CRPseloall))
g.12CRPseloall1 <- g.12CRPseloall1 + stat_boxplot()
g.12CRPseloall1 <- g.12CRPseloall1 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality CRPseloall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_1_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPseloall1)
dev.off()
remove(g.12CRPseloall1)

g.22CRPseloall1 <- ggplot(data221, aes(factor(indicators), CRPseloall))
g.22CRPseloall1 <- g.22CRPseloall1 + stat_boxplot()
g.22CRPseloall1 <- g.22CRPseloall1 + facet_grid(cov2~observations) + opts(title = "2 Class MLR low quality CRPseloall SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.22included_1_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.22CRPseloall1)
dev.off()
remove(g.22CRPseloall1)

g.11gammase1 <- ggplot(data111, aes(factor(indicators), gammase))
g.11gammase1 <- ggplot(data111c, aes(factor(indicators), gammase))
g.11gammase1 <- g.11gammase1 + stat_boxplot()
g.11gammase1 <- g.11gammase1 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality gammase SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_1_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.11gammase1)
dev.off()
remove(g.11gammase1)

g.21gammase1 <- ggplot(data211, aes(factor(indicators), gammase))
g.21gammase1 <- ggplot(data211c, aes(factor(indicators), gammase))
g.21gammase1 <- g.21gammase1 + stat_boxplot()
g.21gammase1 <- g.21gammase1 + facet_grid(cov2~observations) + opts(title = "2 Class MLR high quality gammase SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.21included_1_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.21gammase1)
dev.off()
remove(g.21gammase1)

g.12gammase1 <- ggplot(data121, aes(factor(indicators), gammase))
g.12gammase1 <- ggplot(data121c, aes(factor(indicators), gammase))
g.12gammase1 <- g.12gammase1 + stat_boxplot()
g.12gammase1 <- g.12gammase1 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality gammase SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_1_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.12gammase1)
dev.off()
remove(g.12gammase1)

g.22gammase1 <- ggplot(data221, aes(factor(indicators), gammase))
g.22gammase1 <- ggplot(data221c, aes(factor(indicators), gammase))
g.22gammase1 <- g.22gammase1 + stat_boxplot()
g.22gammase1 <- g.22gammase1 + facet_grid(cov2~observations) + opts(title = "2 Class MLR low quality gammase SE outliers = included")
png(filename = "E://Master's//Data Meeting Revisions//g.22included_1_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.22gammase1)
dev.off()
remove(g.22gammase1)

g.11L1prop2 <- ggplot(data112, aes(factor(indicators), L1prop))
g.11L1prop2 <- g.11L1prop2 + stat_boxplot()
g.11L1prop2 <- g.11L1prop2 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality L1prop SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_1_L1prop.png", width = 1000, height = 1000, units = 'px')
print(g.11L1prop2)
dev.off()
remove(g.11L1prop2)

g.12L1prop2 <- ggplot(data122, aes(factor(indicators), L1prop))
g.12L1prop2 <- g.12L1prop2 + stat_boxplot()
g.12L1prop2 <- g.12L1prop2 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality L1prop SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_1_L1prop.png", width = 1000, height = 1000, units = 'px')
print(g.12L1prop2)
dev.off()
remove(g.12L1prop2)

g.11L2prop2 <- ggplot(data112, aes(factor(indicators), L2prop))
g.11L2prop2 <- g.11L2prop2 + stat_boxplot()
g.11L2prop2 <- g.11L2prop2 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality L2prop SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_1_L2prop.png", width = 1000, height = 1000, units = 'px')
print(g.11L2prop2)
dev.off()
remove(g.11L2prop2)

g.12L2prop2 <- ggplot(data122, aes(factor(indicators), L2prop))
g.12L2prop2 <- g.12L2prop2 + stat_boxplot()
g.12L2prop2 <- g.12L2prop2 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality L2prop SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_1_L2prop.png", width = 1000, height = 1000, units = 'px')
print(g.12L2prop2)
dev.off()
remove(g.12L2prop2)

g.11CRPhiall2 <- ggplot(data112, aes(factor(indicators), CRPhiall))
g.11CRPhiall2 <- g.11CRPhiall2 + stat_boxplot()
g.11CRPhiall2 <- g.11CRPhiall2 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality CRPhiall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_1_CRPhiall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPhiall2)
dev.off()
remove(g.11CRPhiall2)

g.12CRPhiall2 <- ggplot(data122, aes(factor(indicators), CRPhiall))
g.12CRPhiall2 <- g.12CRPhiall2 + stat_boxplot()
g.12CRPhiall2 <- g.12CRPhiall2 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality CRPhiall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_1_CRPhiall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPhiall2)
dev.off()
remove(g.12CRPhiall2)

g.11CRPloall2 <- ggplot(data112, aes(factor(indicators), CRPloall))
g.11CRPloall2 <- g.11CRPloall2 + stat_boxplot()
g.11CRPloall2 <- g.11CRPloall2 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality CRPloall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_1_CRPloall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPloall2)
dev.off()
remove(g.11CRPloall2)

g.12CRPloall2 <- ggplot(data122, aes(factor(indicators), CRPloall))
g.12CRPloall2 <- g.12CRPloall2 + stat_boxplot()
g.12CRPloall2 <- g.12CRPloall2 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality CRPloall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_1_CRPloall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPloall2)
dev.off()
remove(g.12CRPloall2)

g.11gamma2 <- ggplot(data112, aes(factor(indicators), gamma))
g.11gamma2 <- ggplot(data112c, aes(factor(indicators), gamma))
g.11gamma2 <- g.11gamma2 + stat_boxplot()
g.11gamma2 <- g.11gamma2 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality gamma SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_1_gamma.png", width = 1000, height = 1000, units = 'px')
print(g.11gamma2)
dev.off()
remove(g.11gamma2)

g.12gamma2 <- ggplot(data122, aes(factor(indicators), gamma))
g.12gamma2 <- ggplot(data122c, aes(factor(indicators), gamma))
g.12gamma2 <- g.12gamma2 + stat_boxplot()
g.12gamma2 <- g.12gamma2 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality gamma SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_1_gamma.png", width = 1000, height = 1000, units = 'px')
print(g.12gamma2)
dev.off()
remove(g.12gamma2)

g.11L1propse2 <- ggplot(data112, aes(factor(indicators), L1propse))
g.11L1propse2 <- g.11L1propse2 + stat_boxplot()
g.11L1propse2 <- g.11L1propse2 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality L1propse SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_1_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.11L1propse2)
dev.off()
remove(g.11L1propse2)

g.21L1propse2 <- ggplot(data212, aes(factor(indicators), L1propse))
g.21L1propse2 <- g.21L1propse2 + stat_boxplot()
g.21L1propse2 <- g.21L1propse2 + facet_grid(cov2~observations) + opts(title = "2 Class MLR high quality L1propse SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.21excluded_1_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.21L1propse2)
dev.off()
remove(g.21L1propse2)

g.12L1propse2 <- ggplot(data122, aes(factor(indicators), L1propse))
g.12L1propse2 <- g.12L1propse2 + stat_boxplot()
g.12L1propse2 <- g.12L1propse2 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality L1propse SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_1_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.12L1propse2)
dev.off()
remove(g.12L1propse2)

g.22L1propse2 <- ggplot(data222, aes(factor(indicators), L1propse))
g.22L1propse2 <- g.22L1propse2 + stat_boxplot()
g.22L1propse2 <- g.22L1propse2 + facet_grid(cov2~observations) + opts(title = "2 Class MLR low quality L1propse SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.22excluded_1_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.22L1propse2)
dev.off()
remove(g.22L1propse2)

g.11CRPsehiall2 <- ggplot(data112, aes(factor(indicators), CRPsehiall))
g.11CRPsehiall2 <- g.11CRPsehiall2 + stat_boxplot()
g.11CRPsehiall2 <- g.11CRPsehiall2 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality CRPsehiall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_1_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPsehiall2)
dev.off()
remove(g.11CRPsehiall2)

g.21CRPsehiall2 <- ggplot(data212, aes(factor(indicators), CRPsehiall))
g.21CRPsehiall2 <- g.21CRPsehiall2 + stat_boxplot()
g.21CRPsehiall2 <- g.21CRPsehiall2 + facet_grid(cov2~observations) + opts(title = "2 Class MLR high quality CRPsehiall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.21excluded_1_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.21CRPsehiall2)
dev.off()
remove(g.21CRPsehiall2)

g.12CRPsehiall2 <- ggplot(data122, aes(factor(indicators), CRPsehiall))
g.12CRPsehiall2 <- g.12CRPsehiall2 + stat_boxplot()
g.12CRPsehiall2 <- g.12CRPsehiall2 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality CRPsehiall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_1_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPsehiall2)
dev.off()
remove(g.12CRPsehiall2)

g.22CRPsehiall2 <- ggplot(data222, aes(factor(indicators), CRPsehiall))
g.22CRPsehiall2 <- g.22CRPsehiall2 + stat_boxplot()
g.22CRPsehiall2 <- g.22CRPsehiall2 + facet_grid(cov2~observations) + opts(title = "2 Class MLR low quality CRPsehiall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.22excluded_1_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.22CRPsehiall2)
dev.off()
remove(g.22CRPsehiall2)

g.11CRPseloall2 <- ggplot(data112, aes(factor(indicators), CRPseloall))
g.11CRPseloall2 <- g.11CRPseloall2 + stat_boxplot()
g.11CRPseloall2 <- g.11CRPseloall2 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality CRPseloall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_1_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPseloall2)
dev.off()
remove(g.11CRPseloall2)

g.21CRPseloall2 <- ggplot(data212, aes(factor(indicators), CRPseloall))
g.21CRPseloall2 <- g.21CRPseloall2 + stat_boxplot()
g.21CRPseloall2 <- g.21CRPseloall2 + facet_grid(cov2~observations) + opts(title = "2 Class MLR high quality CRPseloall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.21excluded_1_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.21CRPseloall2)
dev.off()
remove(g.21CRPseloall2)

g.12CRPseloall2 <- ggplot(data122, aes(factor(indicators), CRPseloall))
g.12CRPseloall2 <- g.12CRPseloall2 + stat_boxplot()
g.12CRPseloall2 <- g.12CRPseloall2 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality CRPseloall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_1_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPseloall2)
dev.off()
remove(g.12CRPseloall2)

g.22CRPseloall2 <- ggplot(data222, aes(factor(indicators), CRPseloall))
g.22CRPseloall2 <- g.22CRPseloall2 + stat_boxplot()
g.22CRPseloall2 <- g.22CRPseloall2 + facet_grid(cov2~observations) + opts(title = "2 Class MLR low quality CRPseloall SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.22excluded_1_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.22CRPseloall2)
dev.off()
remove(g.22CRPseloall2)

g.11gammase2 <- ggplot(data112, aes(factor(indicators), gammase))
g.11gammase2 <- ggplot(data112c, aes(factor(indicators), gammase))
g.11gammase2 <- g.11gammase2 + stat_boxplot()
g.11gammase2 <- g.11gammase2 + facet_grid(cov2~observations) + opts(title = "2 Class ML high quality gammase SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_1_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.11gammase2)
dev.off()
remove(g.11gammase2)

g.21gammase2 <- ggplot(data212, aes(factor(indicators), gammase))
g.21gammase2 <- ggplot(data212c, aes(factor(indicators), gammase))
g.21gammase2 <- g.21gammase2 + stat_boxplot()
g.21gammase2 <- g.21gammase2 + facet_grid(cov2~observations) + opts(title = "2 Class MLR high quality gammase SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.21excluded_1_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.21gammase2)
dev.off()
remove(g.21gammase2)

g.12gammase2 <- ggplot(data122, aes(factor(indicators), gammase))
g.12gammase2 <- ggplot(data122c, aes(factor(indicators), gammase))
g.12gammase2 <- g.12gammase2 + stat_boxplot()
g.12gammase2 <- g.12gammase2 + facet_grid(cov2~observations) + opts(title = "2 Class ML low quality gammase SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_1_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.12gammase2)
dev.off()
remove(g.12gammase2)

g.22gammase2 <- ggplot(data222, aes(factor(indicators), gammase))
g.22gammase2 <- ggplot(data222c, aes(factor(indicators), gammase))
g.22gammase2 <- g.22gammase2 + stat_boxplot()
g.22gammase2 <- g.22gammase2 + facet_grid(cov2~observations) + opts(title = "2 Class MLR low quality gammase SE outliers = excluded")
png(filename = "E://Master's//Data Meeting Revisions//g.22excluded_1_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.22gammase2)
dev.off()
remove(g.22gammase2)

