library(ggplot2)
library(foreign)
memory.limit(size = 4095)
class.3 <- read.spss("C:\\Users\\icarlso1\\Simulation\\Programs\\LCA 3-Class\\Data\\LCA 3-Class se outlier 1.30.1.sav")
memory.limit(size = 4095)
mydataf = data.frame(class.3)

data111 <- subset(mydataf, se==1 & quality== 1 & in2==1)
data111c <- subset(mydataf, se==1 & quality==1 & cov2 != 1 & in2==1)
data211 <- subset(mydataf, se==2 & quality== 1 & in2==1)
data211c <- subset(mydataf, se==2 & quality==1 & cov2 != 1 & in2==1)
data121 <- subset(mydataf, se==1 & quality== 2 & in2==1)
data121c <- subset(mydataf, se==1 & quality==2 & cov2 != 1 & in2==1)
data221 <- subset(mydataf, se==2 & quality== 2 & in2==1)
data221c <- subset(mydataf, se==2 & quality==2 & cov2 != 1 & in2==1)
data131 <- subset(mydataf, se==1 & quality== 3 & in2==1)
data131c <- subset(mydataf, se==1 & quality==3 & cov2 != 1 & in2==1)
data231 <- subset(mydataf, se==2 & quality== 3 & in2==1)
data231c <- subset(mydataf, se==2 & quality==3 & cov2 != 1 & in2==1)
data112 <- subset(mydataf, se==1 & quality== 1 &is.na(seoutlier) & in2==1)
data112c <- subset(mydataf, se==1 & quality==1 & cov2 != 1 &is.na(seoutlier) & in2==1)
data212 <- subset(mydataf, se==2 & quality== 1 &is.na(seoutlier) & in2==1)
data212c <- subset(mydataf, se==2 & quality==1 & cov2 != 1 &is.na(seoutlier) & in2==1)
data122 <- subset(mydataf, se==1 & quality== 2 &is.na(seoutlier) & in2==1)
data122c <- subset(mydataf, se==1 & quality==2 & cov2 != 1 &is.na(seoutlier) & in2==1)
data222 <- subset(mydataf, se==2 & quality== 2 &is.na(seoutlier) & in2==1)
data222c <- subset(mydataf, se==2 & quality==2 & cov2 != 1 &is.na(seoutlier) & in2==1)
data132 <- subset(mydataf, se==1 & quality== 3 &is.na(seoutlier) & in2==1)
data132c <- subset(mydataf, se==1 & quality==3 & cov2 != 1 &is.na(seoutlier) & in2==1)
data232 <- subset(mydataf, se==2 & quality== 3 &is.na(seoutlier) & in2==1)
data232c <- subset(mydataf, se==2 & quality==3 & cov2 != 1 &is.na(seoutlier) & in2==1)

g.11L1prop1 <- ggplot(data111, aes(factor(indicators), L1prop))
g.11L1prop1 <- g.11L1prop1 + stat_boxplot()
g.11L1prop1 <- g.11L1prop1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 L1prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_L1prop.png", width = 1000, height = 1000, units = 'px')
print(g.11L1prop1)
dev.off()
remove(g.11L1prop1)

g.12L1prop1 <- ggplot(data121, aes(factor(indicators), L1prop))
g.12L1prop1 <- g.12L1prop1 + stat_boxplot()
g.12L1prop1 <- g.12L1prop1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 L1prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_L1prop.png", width = 1000, height = 1000, units = 'px')
print(g.12L1prop1)
dev.off()
remove(g.12L1prop1)

g.13L1prop1 <- ggplot(data131, aes(factor(indicators), L1prop))
g.13L1prop1 <- g.13L1prop1 + stat_boxplot()
g.13L1prop1 <- g.13L1prop1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 L1prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_L1prop.png", width = 1000, height = 1000, units = 'px')
print(g.13L1prop1)
dev.off()
remove(g.13L1prop1)

g.11L2prop1 <- ggplot(data111, aes(factor(indicators), L2prop))
g.11L2prop1 <- g.11L2prop1 + stat_boxplot()
g.11L2prop1 <- g.11L2prop1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 L2prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_L2prop.png", width = 1000, height = 1000, units = 'px')
print(g.11L2prop1)
dev.off()
remove(g.11L2prop1)

g.12L2prop1 <- ggplot(data121, aes(factor(indicators), L2prop))
g.12L2prop1 <- g.12L2prop1 + stat_boxplot()
g.12L2prop1 <- g.12L2prop1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 L2prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_L2prop.png", width = 1000, height = 1000, units = 'px')
print(g.12L2prop1)
dev.off()
remove(g.12L2prop1)

g.13L2prop1 <- ggplot(data131, aes(factor(indicators), L2prop))
g.13L2prop1 <- g.13L2prop1 + stat_boxplot()
g.13L2prop1 <- g.13L2prop1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 L2prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_L2prop.png", width = 1000, height = 1000, units = 'px')
print(g.13L2prop1)
dev.off()
remove(g.13L2prop1)

g.11L3prop1 <- ggplot(data111, aes(factor(indicators), L3prop))
g.11L3prop1 <- g.11L3prop1 + stat_boxplot()
g.11L3prop1 <- g.11L3prop1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 L3prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_L3prop.png", width = 1000, height = 1000, units = 'px')
print(g.11L3prop1)
dev.off()
remove(g.11L3prop1)

g.12L3prop1 <- ggplot(data121, aes(factor(indicators), L3prop))
g.12L3prop1 <- g.12L3prop1 + stat_boxplot()
g.12L3prop1 <- g.12L3prop1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 L3prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_L3prop.png", width = 1000, height = 1000, units = 'px')
print(g.12L3prop1)
dev.off()
remove(g.12L3prop1)

g.13L3prop1 <- ggplot(data131, aes(factor(indicators), L3prop))
g.13L3prop1 <- g.13L3prop1 + stat_boxplot()
g.13L3prop1 <- g.13L3prop1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 L3prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_L3prop.png", width = 1000, height = 1000, units = 'px')
print(g.13L3prop1)
dev.off()
remove(g.13L3prop1)

g.11CRPhiall1 <- ggplot(data111, aes(factor(indicators), CRPhiall))
g.11CRPhiall1 <- g.11CRPhiall1 + stat_boxplot()
g.11CRPhiall1 <- g.11CRPhiall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 CRPhiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_CRPhiall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPhiall1)
dev.off()
remove(g.11CRPhiall1)

g.12CRPhiall1 <- ggplot(data121, aes(factor(indicators), CRPhiall))
g.12CRPhiall1 <- g.12CRPhiall1 + stat_boxplot()
g.12CRPhiall1 <- g.12CRPhiall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 CRPhiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_CRPhiall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPhiall1)
dev.off()
remove(g.12CRPhiall1)

g.13CRPhiall1 <- ggplot(data131, aes(factor(indicators), CRPhiall))
g.13CRPhiall1 <- g.13CRPhiall1 + stat_boxplot()
g.13CRPhiall1 <- g.13CRPhiall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 CRPhiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_CRPhiall.png", width = 1000, height = 1000, units = 'px')
print(g.13CRPhiall1)
dev.off()
remove(g.13CRPhiall1)

g.11CRPloall1 <- ggplot(data111, aes(factor(indicators), CRPloall))
g.11CRPloall1 <- g.11CRPloall1 + stat_boxplot()
g.11CRPloall1 <- g.11CRPloall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 CRPloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_CRPloall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPloall1)
dev.off()
remove(g.11CRPloall1)

g.12CRPloall1 <- ggplot(data121, aes(factor(indicators), CRPloall))
g.12CRPloall1 <- g.12CRPloall1 + stat_boxplot()
g.12CRPloall1 <- g.12CRPloall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 CRPloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_CRPloall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPloall1)
dev.off()
remove(g.12CRPloall1)

g.13CRPloall1 <- ggplot(data131, aes(factor(indicators), CRPloall))
g.13CRPloall1 <- g.13CRPloall1 + stat_boxplot()
g.13CRPloall1 <- g.13CRPloall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 CRPloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_CRPloall.png", width = 1000, height = 1000, units = 'px')
print(g.13CRPloall1)
dev.off()
remove(g.13CRPloall1)

g.11gamma1 <- ggplot(data111, aes(factor(indicators), gamma))
g.11gamma1 <- ggplot(data111c, aes(factor(indicators), gamma))
g.11gamma1 <- g.11gamma1 + stat_boxplot()
g.11gamma1 <- g.11gamma1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 gamma ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_gamma.png", width = 1000, height = 1000, units = 'px')
print(g.11gamma1)
dev.off()
remove(g.11gamma1)

g.12gamma1 <- ggplot(data121, aes(factor(indicators), gamma))
g.12gamma1 <- ggplot(data121c, aes(factor(indicators), gamma))
g.12gamma1 <- g.12gamma1 + stat_boxplot()
g.12gamma1 <- g.12gamma1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 gamma ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_gamma.png", width = 1000, height = 1000, units = 'px')
print(g.12gamma1)
dev.off()
remove(g.12gamma1)

g.13gamma1 <- ggplot(data131, aes(factor(indicators), gamma))
g.13gamma1 <- ggplot(data131c, aes(factor(indicators), gamma))
g.13gamma1 <- g.13gamma1 + stat_boxplot()
g.13gamma1 <- g.13gamma1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 gamma ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_gamma.png", width = 1000, height = 1000, units = 'px')
print(g.13gamma1)
dev.off()
remove(g.13gamma1)

g.11L1propse1 <- ggplot(data111, aes(factor(indicators), L1propse))
g.11L1propse1 <- g.11L1propse1 + stat_boxplot()
g.11L1propse1 <- g.11L1propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.11L1propse1)
dev.off()
remove(g.11L1propse1)

g.21L1propse1 <- ggplot(data211, aes(factor(indicators), L1propse))
g.21L1propse1 <- g.21L1propse1 + stat_boxplot()
g.21L1propse1 <- g.21L1propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 1 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.21included_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.21L1propse1)
dev.off()
remove(g.21L1propse1)

g.12L1propse1 <- ggplot(data121, aes(factor(indicators), L1propse))
g.12L1propse1 <- g.12L1propse1 + stat_boxplot()
g.12L1propse1 <- g.12L1propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.12L1propse1)
dev.off()
remove(g.12L1propse1)

g.22L1propse1 <- ggplot(data221, aes(factor(indicators), L1propse))
g.22L1propse1 <- g.22L1propse1 + stat_boxplot()
g.22L1propse1 <- g.22L1propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 2 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.22included_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.22L1propse1)
dev.off()
remove(g.22L1propse1)

g.13L1propse1 <- ggplot(data131, aes(factor(indicators), L1propse))
g.13L1propse1 <- g.13L1propse1 + stat_boxplot()
g.13L1propse1 <- g.13L1propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.13L1propse1)
dev.off()
remove(g.13L1propse1)

g.23L1propse1 <- ggplot(data231, aes(factor(indicators), L1propse))
g.23L1propse1 <- g.23L1propse1 + stat_boxplot()
g.23L1propse1 <- g.23L1propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 3 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.23included_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.23L1propse1)
dev.off()
remove(g.23L1propse1)

g.11L2propse1 <- ggplot(data111, aes(factor(indicators), L2propse))
g.11L2propse1 <- g.11L2propse1 + stat_boxplot()
g.11L2propse1 <- g.11L2propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.11L2propse1)
dev.off()
remove(g.11L2propse1)

g.21L2propse1 <- ggplot(data211, aes(factor(indicators), L2propse))
g.21L2propse1 <- g.21L2propse1 + stat_boxplot()
g.21L2propse1 <- g.21L2propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 1 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.21included_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.21L2propse1)
dev.off()
remove(g.21L2propse1)

g.12L2propse1 <- ggplot(data121, aes(factor(indicators), L2propse))
g.12L2propse1 <- g.12L2propse1 + stat_boxplot()
g.12L2propse1 <- g.12L2propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.12L2propse1)
dev.off()
remove(g.12L2propse1)

g.22L2propse1 <- ggplot(data221, aes(factor(indicators), L2propse))
g.22L2propse1 <- g.22L2propse1 + stat_boxplot()
g.22L2propse1 <- g.22L2propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 2 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.22included_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.22L2propse1)
dev.off()
remove(g.22L2propse1)

g.13L2propse1 <- ggplot(data131, aes(factor(indicators), L2propse))
g.13L2propse1 <- g.13L2propse1 + stat_boxplot()
g.13L2propse1 <- g.13L2propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.13L2propse1)
dev.off()
remove(g.13L2propse1)

g.23L2propse1 <- ggplot(data231, aes(factor(indicators), L2propse))
g.23L2propse1 <- g.23L2propse1 + stat_boxplot()
g.23L2propse1 <- g.23L2propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 3 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.23included_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.23L2propse1)
dev.off()
remove(g.23L2propse1)

g.11L3propse1 <- ggplot(data111, aes(factor(indicators), L3propse))
g.11L3propse1 <- g.11L3propse1 + stat_boxplot()
g.11L3propse1 <- g.11L3propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.11L3propse1)
dev.off()
remove(g.11L3propse1)

g.21L3propse1 <- ggplot(data211, aes(factor(indicators), L3propse))
g.21L3propse1 <- g.21L3propse1 + stat_boxplot()
g.21L3propse1 <- g.21L3propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 1 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.21included_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.21L3propse1)
dev.off()
remove(g.21L3propse1)

g.12L3propse1 <- ggplot(data121, aes(factor(indicators), L3propse))
g.12L3propse1 <- g.12L3propse1 + stat_boxplot()
g.12L3propse1 <- g.12L3propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.12L3propse1)
dev.off()
remove(g.12L3propse1)

g.22L3propse1 <- ggplot(data221, aes(factor(indicators), L3propse))
g.22L3propse1 <- g.22L3propse1 + stat_boxplot()
g.22L3propse1 <- g.22L3propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 2 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.22included_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.22L3propse1)
dev.off()
remove(g.22L3propse1)

g.13L3propse1 <- ggplot(data131, aes(factor(indicators), L3propse))
g.13L3propse1 <- g.13L3propse1 + stat_boxplot()
g.13L3propse1 <- g.13L3propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.13L3propse1)
dev.off()
remove(g.13L3propse1)

g.23L3propse1 <- ggplot(data231, aes(factor(indicators), L3propse))
g.23L3propse1 <- g.23L3propse1 + stat_boxplot()
g.23L3propse1 <- g.23L3propse1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 3 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.23included_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.23L3propse1)
dev.off()
remove(g.23L3propse1)

g.11CRPsehiall1 <- ggplot(data111, aes(factor(indicators), CRPsehiall))
g.11CRPsehiall1 <- g.11CRPsehiall1 + stat_boxplot()
g.11CRPsehiall1 <- g.11CRPsehiall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPsehiall1)
dev.off()
remove(g.11CRPsehiall1)

g.21CRPsehiall1 <- ggplot(data211, aes(factor(indicators), CRPsehiall))
g.21CRPsehiall1 <- g.21CRPsehiall1 + stat_boxplot()
g.21CRPsehiall1 <- g.21CRPsehiall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 1 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.21included_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.21CRPsehiall1)
dev.off()
remove(g.21CRPsehiall1)

g.12CRPsehiall1 <- ggplot(data121, aes(factor(indicators), CRPsehiall))
g.12CRPsehiall1 <- g.12CRPsehiall1 + stat_boxplot()
g.12CRPsehiall1 <- g.12CRPsehiall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPsehiall1)
dev.off()
remove(g.12CRPsehiall1)

g.22CRPsehiall1 <- ggplot(data221, aes(factor(indicators), CRPsehiall))
g.22CRPsehiall1 <- g.22CRPsehiall1 + stat_boxplot()
g.22CRPsehiall1 <- g.22CRPsehiall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 2 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.22included_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.22CRPsehiall1)
dev.off()
remove(g.22CRPsehiall1)

g.13CRPsehiall1 <- ggplot(data131, aes(factor(indicators), CRPsehiall))
g.13CRPsehiall1 <- g.13CRPsehiall1 + stat_boxplot()
g.13CRPsehiall1 <- g.13CRPsehiall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.13CRPsehiall1)
dev.off()
remove(g.13CRPsehiall1)

g.23CRPsehiall1 <- ggplot(data231, aes(factor(indicators), CRPsehiall))
g.23CRPsehiall1 <- g.23CRPsehiall1 + stat_boxplot()
g.23CRPsehiall1 <- g.23CRPsehiall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 3 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.23included_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.23CRPsehiall1)
dev.off()
remove(g.23CRPsehiall1)

g.11CRPseloall1 <- ggplot(data111, aes(factor(indicators), CRPseloall))
g.11CRPseloall1 <- g.11CRPseloall1 + stat_boxplot()
g.11CRPseloall1 <- g.11CRPseloall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPseloall1)
dev.off()
remove(g.11CRPseloall1)

g.21CRPseloall1 <- ggplot(data211, aes(factor(indicators), CRPseloall))
g.21CRPseloall1 <- g.21CRPseloall1 + stat_boxplot()
g.21CRPseloall1 <- g.21CRPseloall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 1 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.21included_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.21CRPseloall1)
dev.off()
remove(g.21CRPseloall1)

g.12CRPseloall1 <- ggplot(data121, aes(factor(indicators), CRPseloall))
g.12CRPseloall1 <- g.12CRPseloall1 + stat_boxplot()
g.12CRPseloall1 <- g.12CRPseloall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPseloall1)
dev.off()
remove(g.12CRPseloall1)

g.22CRPseloall1 <- ggplot(data221, aes(factor(indicators), CRPseloall))
g.22CRPseloall1 <- g.22CRPseloall1 + stat_boxplot()
g.22CRPseloall1 <- g.22CRPseloall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 2 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.22included_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.22CRPseloall1)
dev.off()
remove(g.22CRPseloall1)

g.13CRPseloall1 <- ggplot(data131, aes(factor(indicators), CRPseloall))
g.13CRPseloall1 <- g.13CRPseloall1 + stat_boxplot()
g.13CRPseloall1 <- g.13CRPseloall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.13CRPseloall1)
dev.off()
remove(g.13CRPseloall1)

g.23CRPseloall1 <- ggplot(data231, aes(factor(indicators), CRPseloall))
g.23CRPseloall1 <- g.23CRPseloall1 + stat_boxplot()
g.23CRPseloall1 <- g.23CRPseloall1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 3 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.23included_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.23CRPseloall1)
dev.off()
remove(g.23CRPseloall1)

g.11gammase1 <- ggplot(data111, aes(factor(indicators), gammase))
g.11gammase1 <- ggplot(data111c, aes(factor(indicators), gammase))
g.11gammase1 <- g.11gammase1 + stat_boxplot()
g.11gammase1 <- g.11gammase1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 1 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.11included_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.11gammase1)
dev.off()
remove(g.11gammase1)

g.21gammase1 <- ggplot(data211, aes(factor(indicators), gammase))
g.21gammase1 <- ggplot(data211c, aes(factor(indicators), gammase))
g.21gammase1 <- g.21gammase1 + stat_boxplot()
g.21gammase1 <- g.21gammase1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 1 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.21included_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.21gammase1)
dev.off()
remove(g.21gammase1)

g.12gammase1 <- ggplot(data121, aes(factor(indicators), gammase))
g.12gammase1 <- ggplot(data121c, aes(factor(indicators), gammase))
g.12gammase1 <- g.12gammase1 + stat_boxplot()
g.12gammase1 <- g.12gammase1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 2 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.12included_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.12gammase1)
dev.off()
remove(g.12gammase1)

g.22gammase1 <- ggplot(data221, aes(factor(indicators), gammase))
g.22gammase1 <- ggplot(data221c, aes(factor(indicators), gammase))
g.22gammase1 <- g.22gammase1 + stat_boxplot()
g.22gammase1 <- g.22gammase1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 2 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.22included_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.22gammase1)
dev.off()
remove(g.22gammase1)

g.13gammase1 <- ggplot(data131, aes(factor(indicators), gammase))
g.13gammase1 <- ggplot(data131c, aes(factor(indicators), gammase))
g.13gammase1 <- g.13gammase1 + stat_boxplot()
g.13gammase1 <- g.13gammase1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 1 quality = 3 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.13included_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.13gammase1)
dev.off()
remove(g.13gammase1)

g.23gammase1 <- ggplot(data231, aes(factor(indicators), gammase))
g.23gammase1 <- ggplot(data231c, aes(factor(indicators), gammase))
g.23gammase1 <- g.23gammase1 + stat_boxplot()
g.23gammase1 <- g.23gammase1 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = included se = 2 quality = 3 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.23included_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.23gammase1)
dev.off()
remove(g.23gammase1)

g.11L1prop2 <- ggplot(data112, aes(factor(indicators), L1prop))
g.11L1prop2 <- g.11L1prop2 + stat_boxplot()
g.11L1prop2 <- g.11L1prop2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 L1prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_L1prop.png", width = 1000, height = 1000, units = 'px')
print(g.11L1prop2)
dev.off()
remove(g.11L1prop2)

g.12L1prop2 <- ggplot(data122, aes(factor(indicators), L1prop))
g.12L1prop2 <- g.12L1prop2 + stat_boxplot()
g.12L1prop2 <- g.12L1prop2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 L1prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_L1prop.png", width = 1000, height = 1000, units = 'px')
print(g.12L1prop2)
dev.off()
remove(g.12L1prop2)

g.13L1prop2 <- ggplot(data132, aes(factor(indicators), L1prop))
g.13L1prop2 <- g.13L1prop2 + stat_boxplot()
g.13L1prop2 <- g.13L1prop2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 L1prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_L1prop.png", width = 1000, height = 1000, units = 'px')
print(g.13L1prop2)
dev.off()
remove(g.13L1prop2)

g.11L2prop2 <- ggplot(data112, aes(factor(indicators), L2prop))
g.11L2prop2 <- g.11L2prop2 + stat_boxplot()
g.11L2prop2 <- g.11L2prop2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 L2prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_L2prop.png", width = 1000, height = 1000, units = 'px')
print(g.11L2prop2)
dev.off()
remove(g.11L2prop2)

g.12L2prop2 <- ggplot(data122, aes(factor(indicators), L2prop))
g.12L2prop2 <- g.12L2prop2 + stat_boxplot()
g.12L2prop2 <- g.12L2prop2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 L2prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_L2prop.png", width = 1000, height = 1000, units = 'px')
print(g.12L2prop2)
dev.off()
remove(g.12L2prop2)

g.13L2prop2 <- ggplot(data132, aes(factor(indicators), L2prop))
g.13L2prop2 <- g.13L2prop2 + stat_boxplot()
g.13L2prop2 <- g.13L2prop2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 L2prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_L2prop.png", width = 1000, height = 1000, units = 'px')
print(g.13L2prop2)
dev.off()
remove(g.13L2prop2)

g.11L3prop2 <- ggplot(data112, aes(factor(indicators), L3prop))
g.11L3prop2 <- g.11L3prop2 + stat_boxplot()
g.11L3prop2 <- g.11L3prop2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 L3prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_L3prop.png", width = 1000, height = 1000, units = 'px')
print(g.11L3prop2)
dev.off()
remove(g.11L3prop2)

g.12L3prop2 <- ggplot(data122, aes(factor(indicators), L3prop))
g.12L3prop2 <- g.12L3prop2 + stat_boxplot()
g.12L3prop2 <- g.12L3prop2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 L3prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_L3prop.png", width = 1000, height = 1000, units = 'px')
print(g.12L3prop2)
dev.off()
remove(g.12L3prop2)

g.13L3prop2 <- ggplot(data132, aes(factor(indicators), L3prop))
g.13L3prop2 <- g.13L3prop2 + stat_boxplot()
g.13L3prop2 <- g.13L3prop2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 L3prop ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_L3prop.png", width = 1000, height = 1000, units = 'px')
print(g.13L3prop2)
dev.off()
remove(g.13L3prop2)

g.11CRPhiall2 <- ggplot(data112, aes(factor(indicators), CRPhiall))
g.11CRPhiall2 <- g.11CRPhiall2 + stat_boxplot()
g.11CRPhiall2 <- g.11CRPhiall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 CRPhiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_CRPhiall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPhiall2)
dev.off()
remove(g.11CRPhiall2)

g.12CRPhiall2 <- ggplot(data122, aes(factor(indicators), CRPhiall))
g.12CRPhiall2 <- g.12CRPhiall2 + stat_boxplot()
g.12CRPhiall2 <- g.12CRPhiall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 CRPhiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_CRPhiall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPhiall2)
dev.off()
remove(g.12CRPhiall2)

g.13CRPhiall2 <- ggplot(data132, aes(factor(indicators), CRPhiall))
g.13CRPhiall2 <- g.13CRPhiall2 + stat_boxplot()
g.13CRPhiall2 <- g.13CRPhiall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 CRPhiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_CRPhiall.png", width = 1000, height = 1000, units = 'px')
print(g.13CRPhiall2)
dev.off()
remove(g.13CRPhiall2)

g.11CRPloall2 <- ggplot(data112, aes(factor(indicators), CRPloall))
g.11CRPloall2 <- g.11CRPloall2 + stat_boxplot()
g.11CRPloall2 <- g.11CRPloall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 CRPloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_CRPloall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPloall2)
dev.off()
remove(g.11CRPloall2)

g.12CRPloall2 <- ggplot(data122, aes(factor(indicators), CRPloall))
g.12CRPloall2 <- g.12CRPloall2 + stat_boxplot()
g.12CRPloall2 <- g.12CRPloall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 CRPloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_CRPloall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPloall2)
dev.off()
remove(g.12CRPloall2)

g.13CRPloall2 <- ggplot(data132, aes(factor(indicators), CRPloall))
g.13CRPloall2 <- g.13CRPloall2 + stat_boxplot()
g.13CRPloall2 <- g.13CRPloall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 CRPloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_CRPloall.png", width = 1000, height = 1000, units = 'px')
print(g.13CRPloall2)
dev.off()
remove(g.13CRPloall2)

g.11gamma2 <- ggplot(data112, aes(factor(indicators), gamma))
g.11gamma2 <- ggplot(data112c, aes(factor(indicators), gamma))
g.11gamma2 <- g.11gamma2 + stat_boxplot()
g.11gamma2 <- g.11gamma2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 gamma ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_gamma.png", width = 1000, height = 1000, units = 'px')
print(g.11gamma2)
dev.off()
remove(g.11gamma2)

g.12gamma2 <- ggplot(data122, aes(factor(indicators), gamma))
g.12gamma2 <- ggplot(data122c, aes(factor(indicators), gamma))
g.12gamma2 <- g.12gamma2 + stat_boxplot()
g.12gamma2 <- g.12gamma2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 gamma ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_gamma.png", width = 1000, height = 1000, units = 'px')
print(g.12gamma2)
dev.off()
remove(g.12gamma2)

g.13gamma2 <- ggplot(data132, aes(factor(indicators), gamma))
g.13gamma2 <- ggplot(data132c, aes(factor(indicators), gamma))
g.13gamma2 <- g.13gamma2 + stat_boxplot()
g.13gamma2 <- g.13gamma2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 gamma ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_gamma.png", width = 1000, height = 1000, units = 'px')
print(g.13gamma2)
dev.off()
remove(g.13gamma2)

g.11L1propse2 <- ggplot(data112, aes(factor(indicators), L1propse))
g.11L1propse2 <- g.11L1propse2 + stat_boxplot()
g.11L1propse2 <- g.11L1propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.11L1propse2)
dev.off()
remove(g.11L1propse2)

g.21L1propse2 <- ggplot(data212, aes(factor(indicators), L1propse))
g.21L1propse2 <- g.21L1propse2 + stat_boxplot()
g.21L1propse2 <- g.21L1propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 1 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.21excluded_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.21L1propse2)
dev.off()
remove(g.21L1propse2)

g.12L1propse2 <- ggplot(data122, aes(factor(indicators), L1propse))
g.12L1propse2 <- g.12L1propse2 + stat_boxplot()
g.12L1propse2 <- g.12L1propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.12L1propse2)
dev.off()
remove(g.12L1propse2)

g.22L1propse2 <- ggplot(data222, aes(factor(indicators), L1propse))
g.22L1propse2 <- g.22L1propse2 + stat_boxplot()
g.22L1propse2 <- g.22L1propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 2 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.22excluded_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.22L1propse2)
dev.off()
remove(g.22L1propse2)

g.13L1propse2 <- ggplot(data132, aes(factor(indicators), L1propse))
g.13L1propse2 <- g.13L1propse2 + stat_boxplot()
g.13L1propse2 <- g.13L1propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.13L1propse2)
dev.off()
remove(g.13L1propse2)

g.23L1propse2 <- ggplot(data232, aes(factor(indicators), L1propse))
g.23L1propse2 <- g.23L1propse2 + stat_boxplot()
g.23L1propse2 <- g.23L1propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 3 L1propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.23excluded_2_L1propse.png", width = 1000, height = 1000, units = 'px')
print(g.23L1propse2)
dev.off()
remove(g.23L1propse2)

g.11L2propse2 <- ggplot(data112, aes(factor(indicators), L2propse))
g.11L2propse2 <- g.11L2propse2 + stat_boxplot()
g.11L2propse2 <- g.11L2propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.11L2propse2)
dev.off()
remove(g.11L2propse2)

g.21L2propse2 <- ggplot(data212, aes(factor(indicators), L2propse))
g.21L2propse2 <- g.21L2propse2 + stat_boxplot()
g.21L2propse2 <- g.21L2propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 1 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.21excluded_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.21L2propse2)
dev.off()
remove(g.21L2propse2)

g.12L2propse2 <- ggplot(data122, aes(factor(indicators), L2propse))
g.12L2propse2 <- g.12L2propse2 + stat_boxplot()
g.12L2propse2 <- g.12L2propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.12L2propse2)
dev.off()
remove(g.12L2propse2)

g.22L2propse2 <- ggplot(data222, aes(factor(indicators), L2propse))
g.22L2propse2 <- g.22L2propse2 + stat_boxplot()
g.22L2propse2 <- g.22L2propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 2 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.22excluded_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.22L2propse2)
dev.off()
remove(g.22L2propse2)

g.13L2propse2 <- ggplot(data132, aes(factor(indicators), L2propse))
g.13L2propse2 <- g.13L2propse2 + stat_boxplot()
g.13L2propse2 <- g.13L2propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.13L2propse2)
dev.off()
remove(g.13L2propse2)

g.23L2propse2 <- ggplot(data232, aes(factor(indicators), L2propse))
g.23L2propse2 <- g.23L2propse2 + stat_boxplot()
g.23L2propse2 <- g.23L2propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 3 L2propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.23excluded_2_L2propse.png", width = 1000, height = 1000, units = 'px')
print(g.23L2propse2)
dev.off()
remove(g.23L2propse2)

g.11L3propse2 <- ggplot(data112, aes(factor(indicators), L3propse))
g.11L3propse2 <- g.11L3propse2 + stat_boxplot()
g.11L3propse2 <- g.11L3propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.11L3propse2)
dev.off()
remove(g.11L3propse2)

g.21L3propse2 <- ggplot(data212, aes(factor(indicators), L3propse))
g.21L3propse2 <- g.21L3propse2 + stat_boxplot()
g.21L3propse2 <- g.21L3propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 1 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.21excluded_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.21L3propse2)
dev.off()
remove(g.21L3propse2)

g.12L3propse2 <- ggplot(data122, aes(factor(indicators), L3propse))
g.12L3propse2 <- g.12L3propse2 + stat_boxplot()
g.12L3propse2 <- g.12L3propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.12L3propse2)
dev.off()
remove(g.12L3propse2)

g.22L3propse2 <- ggplot(data222, aes(factor(indicators), L3propse))
g.22L3propse2 <- g.22L3propse2 + stat_boxplot()
g.22L3propse2 <- g.22L3propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 2 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.22excluded_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.22L3propse2)
dev.off()
remove(g.22L3propse2)

g.13L3propse2 <- ggplot(data132, aes(factor(indicators), L3propse))
g.13L3propse2 <- g.13L3propse2 + stat_boxplot()
g.13L3propse2 <- g.13L3propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.13L3propse2)
dev.off()
remove(g.13L3propse2)

g.23L3propse2 <- ggplot(data232, aes(factor(indicators), L3propse))
g.23L3propse2 <- g.23L3propse2 + stat_boxplot()
g.23L3propse2 <- g.23L3propse2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 3 L3propse ")
png(filename = "E://Master's//Data Meeting Revisions//g.23excluded_2_L3propse.png", width = 1000, height = 1000, units = 'px')
print(g.23L3propse2)
dev.off()
remove(g.23L3propse2)

g.11CRPsehiall2 <- ggplot(data112, aes(factor(indicators), CRPsehiall))
g.11CRPsehiall2 <- g.11CRPsehiall2 + stat_boxplot()
g.11CRPsehiall2 <- g.11CRPsehiall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPsehiall2)
dev.off()
remove(g.11CRPsehiall2)

g.21CRPsehiall2 <- ggplot(data212, aes(factor(indicators), CRPsehiall))
g.21CRPsehiall2 <- g.21CRPsehiall2 + stat_boxplot()
g.21CRPsehiall2 <- g.21CRPsehiall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 1 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.21excluded_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.21CRPsehiall2)
dev.off()
remove(g.21CRPsehiall2)

g.12CRPsehiall2 <- ggplot(data122, aes(factor(indicators), CRPsehiall))
g.12CRPsehiall2 <- g.12CRPsehiall2 + stat_boxplot()
g.12CRPsehiall2 <- g.12CRPsehiall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPsehiall2)
dev.off()
remove(g.12CRPsehiall2)

g.22CRPsehiall2 <- ggplot(data222, aes(factor(indicators), CRPsehiall))
g.22CRPsehiall2 <- g.22CRPsehiall2 + stat_boxplot()
g.22CRPsehiall2 <- g.22CRPsehiall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 2 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.22excluded_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.22CRPsehiall2)
dev.off()
remove(g.22CRPsehiall2)

g.13CRPsehiall2 <- ggplot(data132, aes(factor(indicators), CRPsehiall))
g.13CRPsehiall2 <- g.13CRPsehiall2 + stat_boxplot()
g.13CRPsehiall2 <- g.13CRPsehiall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.13CRPsehiall2)
dev.off()
remove(g.13CRPsehiall2)

g.23CRPsehiall2 <- ggplot(data232, aes(factor(indicators), CRPsehiall))
g.23CRPsehiall2 <- g.23CRPsehiall2 + stat_boxplot()
g.23CRPsehiall2 <- g.23CRPsehiall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 3 CRPsehiall ")
png(filename = "E://Master's//Data Meeting Revisions//g.23excluded_2_CRPsehiall.png", width = 1000, height = 1000, units = 'px')
print(g.23CRPsehiall2)
dev.off()
remove(g.23CRPsehiall2)

g.11CRPseloall2 <- ggplot(data112, aes(factor(indicators), CRPseloall))
g.11CRPseloall2 <- g.11CRPseloall2 + stat_boxplot()
g.11CRPseloall2 <- g.11CRPseloall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.11CRPseloall2)
dev.off()
remove(g.11CRPseloall2)

g.21CRPseloall2 <- ggplot(data212, aes(factor(indicators), CRPseloall))
g.21CRPseloall2 <- g.21CRPseloall2 + stat_boxplot()
g.21CRPseloall2 <- g.21CRPseloall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 1 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.21excluded_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.21CRPseloall2)
dev.off()
remove(g.21CRPseloall2)

g.12CRPseloall2 <- ggplot(data122, aes(factor(indicators), CRPseloall))
g.12CRPseloall2 <- g.12CRPseloall2 + stat_boxplot()
g.12CRPseloall2 <- g.12CRPseloall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.12CRPseloall2)
dev.off()
remove(g.12CRPseloall2)

g.22CRPseloall2 <- ggplot(data222, aes(factor(indicators), CRPseloall))
g.22CRPseloall2 <- g.22CRPseloall2 + stat_boxplot()
g.22CRPseloall2 <- g.22CRPseloall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 2 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.22excluded_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.22CRPseloall2)
dev.off()
remove(g.22CRPseloall2)

g.13CRPseloall2 <- ggplot(data132, aes(factor(indicators), CRPseloall))
g.13CRPseloall2 <- g.13CRPseloall2 + stat_boxplot()
g.13CRPseloall2 <- g.13CRPseloall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.13CRPseloall2)
dev.off()
remove(g.13CRPseloall2)

g.23CRPseloall2 <- ggplot(data232, aes(factor(indicators), CRPseloall))
g.23CRPseloall2 <- g.23CRPseloall2 + stat_boxplot()
g.23CRPseloall2 <- g.23CRPseloall2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 3 CRPseloall ")
png(filename = "E://Master's//Data Meeting Revisions//g.23excluded_2_CRPseloall.png", width = 1000, height = 1000, units = 'px')
print(g.23CRPseloall2)
dev.off()
remove(g.23CRPseloall2)

g.11gammase2 <- ggplot(data112, aes(factor(indicators), gammase))
g.11gammase2 <- ggplot(data112c, aes(factor(indicators), gammase))
g.11gammase2 <- g.11gammase2 + stat_boxplot()
g.11gammase2 <- g.11gammase2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 1 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.11excluded_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.11gammase2)
dev.off()
remove(g.11gammase2)

g.21gammase2 <- ggplot(data212, aes(factor(indicators), gammase))
g.21gammase2 <- ggplot(data212c, aes(factor(indicators), gammase))
g.21gammase2 <- g.21gammase2 + stat_boxplot()
g.21gammase2 <- g.21gammase2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 1 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.21excluded_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.21gammase2)
dev.off()
remove(g.21gammase2)

g.12gammase2 <- ggplot(data122, aes(factor(indicators), gammase))
g.12gammase2 <- ggplot(data122c, aes(factor(indicators), gammase))
g.12gammase2 <- g.12gammase2 + stat_boxplot()
g.12gammase2 <- g.12gammase2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 2 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.12excluded_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.12gammase2)
dev.off()
remove(g.12gammase2)

g.22gammase2 <- ggplot(data222, aes(factor(indicators), gammase))
g.22gammase2 <- ggplot(data222c, aes(factor(indicators), gammase))
g.22gammase2 <- g.22gammase2 + stat_boxplot()
g.22gammase2 <- g.22gammase2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 2 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.22excluded_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.22gammase2)
dev.off()
remove(g.22gammase2)

g.13gammase2 <- ggplot(data132, aes(factor(indicators), gammase))
g.13gammase2 <- ggplot(data132c, aes(factor(indicators), gammase))
g.13gammase2 <- g.13gammase2 + stat_boxplot()
g.13gammase2 <- g.13gammase2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 1 quality = 3 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.13excluded_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.13gammase2)
dev.off()
remove(g.13gammase2)

g.23gammase2 <- ggplot(data232, aes(factor(indicators), gammase))
g.23gammase2 <- ggplot(data232c, aes(factor(indicators), gammase))
g.23gammase2 <- g.23gammase2 + stat_boxplot()
g.23gammase2 <- g.23gammase2 + facet_grid(cov2~observations) + opts(title =  "  3 Class  se outliers = excluded se = 2 quality = 3 gammase ")
png(filename = "E://Master's//Data Meeting Revisions//g.23excluded_2_gammase.png", width = 1000, height = 1000, units = 'px')
print(g.23gammase2)
dev.off()
remove(g.23gammase2)

